// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/hayeah/agentboss"
	"github.com/hayeah/agentboss/conf"
)

// Injectors from wire.go:

func InitializeApp() (*App, func(), error) {
	config, err := conf.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	stateDir := config.StateDir
	processStore := agentboss.NewProcessStore(stateDir)
	tmux := agentboss.NewTmux()
	detectorRunner := agentboss.NewDetectorRunner(processStore, tmux, stateDir)
	boss := agentboss.NewBoss(processStore, tmux, detectorRunner)
	mainBoss := NewBoss(processStore, tmux, detectorRunner, boss)
	app := NewApp(mainBoss)
	return app, func() {
	}, nil
}
